### ISSUE TITLE
Threads

### ISSUE THREAD

**Issue by ankith26** [FergusGriggs/Fegaria-Remastered#3]
From what I figure out from your code, you run a lot of threads - Threads in python do not work like they do in C or something, something called GIL exists in python that essentially only allowes one thread of the interpreter to run at any given time. So, making a lot of threads does not increase performance at all, in fact it is the other way. The only usecase for threads in python is when you are doing IO related stuff that do not use much CPU.

**Comment by FergusGriggs** [comment]
Ah, I see, good to know. The 'DrawTerrainMultiThreaded' and 'DrawTerrainMultiThreadedFunc' functions at the top of the 'fegaria_remastered.py' file are purely tests to see if it would speed up rendering, they're not actually called. I should probably remove these from the code, but I wasn't sure if I would need them in the future. The only secondary thread used is the lighting thread. This is just because I thought it would be easier to create a thread every time the last one finished as opposed to creating a system to perform part of the lighting calculations every frame. If the lighting calculations were performed all at once on the main thread, the game would run at around 11 fps. If it will improve performance, I might create the aforementioned system to split up the lighting calculations into manageable chunks that would be run on the main thread every frame.

**Comment by ankith26** [comment]
Yes, it is a good idea to do every CPU intensive task in the same thread in python. But there exist a module called multiprocessing which creates new processes that can run on its own, this is perfect for CPU intensively tasks like your lighting - but multiprocessing bring in a bit of overhead, they not as simple as multithreading.
